version: "2"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./misc/dbdata:/var/lib/postgresql/data
  web:
    # Docker hack to wait until Postgres is up, then run stuff.
    command: ./start.sh
    image: german_media_rss
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      IN_DOCKER: 1
  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -conf /code/misc/caddyfile.conf
    volumes:
      - .:/code
