# Generated by Django 2.1.2 on 2018-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180909_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedWikiWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, unique=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SeedLinks',
        ),
        migrations.DeleteModel(
            name='WikipediaCategory',
        ),
        migrations.AddField(
            model_name='feed',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting'), (1, 'working'), (2, 'success'), (3, 'error')], default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
