# Generated by Django 2.1.2 on 2018-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181010_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_type',
            field=models.CharField(max_length=10),
        ),
    ]
