# Generated by Django 2.1.2 on 2018-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181011_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed_type',
            new_name='version',
        ),
        migrations.AddField(
            model_name='feed',
            name='link',
            field=models.CharField(default='f', max_length=500),
            preserve_default=False,
        ),
    ]
