# Generated by Django 2.1.2 on 2018-10-26 14:40

from django.db import migrations, models
from django.utils.text import slugify


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Website = apps.get_model("main", "Website")
        for instance in Website.objects.all():
            if not instance.slug:
                instance.slug = slugify(instance.url)
                instance.save()

    def reverse_func(apps, schema_editor):
        pass

    dependencies = [
        ('main', '0008_auto_20181025_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
