# Generated by Django 2.1.2 on 2018-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_website_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='posts_per_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
