# Generated by Django 2.1.2 on 2018-10-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181026_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='score',
            new_name='reddits_per_day',
        ),
    ]
