# Generated by Django 2.1.5 on 2019-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190105_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='posts_per_day',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='reddits_per_day',
            field=models.FloatField(null=True),
        ),
    ]
